on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  run_deploy_stg:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Run deploy script
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && ./deploy-stg.sh"

      - name: Cleanup
        run: rm -rf ~/.ssh
